### ISSUE TITLE
BE- Documentación y requerimientos del proyecto

### ISSUE THREAD

**Issue by mancuellofran** [Trycatch-tv/team6-project4-backend#1]
Gestión de tareas y proyectos:
Creación y edición de proyectos (nombre, descripción, fechas, estado, etc.).
Creación y edición de tareas (nombre, descripción, fechas, prioridad, estado, etc.).
Listado y búsqueda de proyectos y tareas.
Visualización de detalles de proyectos y tareas.
Eliminación de proyectos y tareas.
Asignación de tareas a miembros del equipo.

1. Modelado de bases de datos
2. Documento en drive con capturas de pantalla

**Comment by sahernandezz** [comment]
Ya hay una versión preliminar para que pueda ser discutida con los demás miembros del equipo.
**url:** [Link](https://docs.google.com/document/d/1MGgnPPVpULOWXhCRC_wkpmOPv6NvEPso-UdCKAg_kWI/edit#)

**Comment by caroni2021** [comment]
soy nuevo en este medio.. me podrian indicar como trabajan... todo se publica aqui? no hay algun grupo de wsp?

**Comment by mancuellofran** [comment]
> soy nuevo en este medio.. me podrian indicar como trabajan... todo se publica aqui? no hay algun grupo de wsp?

Favor revisa el grupo del slack @caroni2021

**Comment by mancuellofran** [comment]
> Ya hay una versión preliminar para que pueda ser discutida con los demás miembros del equipo. **url:** [https://docs.google.com/document/d/1MGgnPPVpULOWXhCRC_wkpmOPv6NvEPso-UdCKAg_kWI/edit#](url)

Necesitamos definir la prioridad de cada tarea @sahernandezz

**Comment by sahernandezz** [comment]
Ya esta corregido.
**url:** [Link](https://docs.google.com/document/d/1MGgnPPVpULOWXhCRC_wkpmOPv6NvEPso-UdCKAg_kWI/edit#)

**Comment by mancuellofran** [comment]
buen trabajo!
